# Generated by Django 4.1.4 on 2022-12-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod", models.IntegerField(auto_created=True, unique=True)),
                ("nome", models.CharField(max_length=20)),
                ("cod_amigo", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Presente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("tamanho", models.CharField(max_length=2)),
                ("link", models.CharField(max_length=500)),
                ("observacoes", models.CharField(max_length=500)),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="amigosecreto.participante",
                    ),
                ),
            ],
        ),
    ]
