# Generated by Django 4.1.4 on 2022-12-08 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amigosecreto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sorteados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cod_participante", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="participante",
            name="id",
        ),
        migrations.AlterField(
            model_name="participante",
            name="cod",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
